### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by theadanielskocher** [noidsirius/IOI-Translation#14]
Sorry for the question, but can I install this on Windows?

**Comment by EqbalS** [comment]
This project uses Django, and it's deployed via Docker (docker-compose). You can use the docs below to understand how to run Django and Docker on windows:
https://docs.djangoproject.com/en/4.2/howto/windows/
https://docs.docker.com/desktop/install/windows-install/
But the project is a little old and uses old versions of these technologies, so be patient as you might run into quite a few issues.

**Comment by theadanielskocher** [comment]
Thank you for the answer!
